# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0002_auto_20160705_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('file', models.FileField(upload_to='C:\\Programming\\Django\\redcross\\redcross_media\\uploads\\newsletter')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='team_images',
            name='images',
            field=models.FileField(null=True, upload_to='C:\\Programming\\Django\\redcross\\redcross_media\\uploads\\temporary'),
        ),
        migrations.AlterField(
            model_name='top_slider',
            name='images',
            field=models.FileField(null=True, upload_to='C:\\Programming\\Django\\redcross\\redcross_media\\uploads\\temporary'),
        ),
    ]
