# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0003_auto_20160706_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Programming\\Django\\redcross\\redcross_media\\uploads\\alerts'),
        ),
    ]
