# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0005_top_slider_remove_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hometext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_text_1', models.CharField(blank=True, max_length=50, null=True)),
                ('slider_text_2', models.CharField(blank=True, max_length=50, null=True)),
                ('slider_text_3', models.CharField(blank=True, max_length=50, null=True)),
                ('slider_text_4', models.CharField(blank=True, max_length=50, null=True)),
                ('fmr_description', models.CharField(blank=True, max_length=50, null=True)),
                ('bloodbank_description', models.CharField(blank=True, max_length=50, null=True)),
                ('st_john_ambulance_description', models.CharField(blank=True, max_length=50, null=True)),
                ('dm_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
