# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0007_hometext_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='logo',
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name_plural': 'Change Alerts'},
        ),
        migrations.AlterModelOptions(
            name='branch_number',
            options={'verbose_name_plural': 'Change Branch/awards '},
        ),
        migrations.AlterModelOptions(
            name='hometext',
            options={'verbose_name_plural': 'Home Page Text'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Home Page Text'},
        ),
        migrations.AlterModelOptions(
            name='team_images',
            options={'verbose_name_plural': 'Change Our Team'},
        ),
        migrations.AlterModelOptions(
            name='top_slider',
            options={'verbose_name_plural': 'Change Homepage Slider Images'},
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
