# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0008_auto_20160706_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='O', max_length=20, null=True),
        ),
    ]
