# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0009_auto_20160706_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, default='Draft', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, default='Others', max_length=20, null=True),
        ),
    ]
