# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0011_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_slug',
            field=models.SlugField(default='1', editable=False),
        ),
    ]
