# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0013_auto_20160707_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
