# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 21:44
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0014_post_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rti', ckeditor_uploader.fields.RichTextUploadingField()),
                ('teders', ckeditor_uploader.fields.RichTextUploadingField()),
                ('career', ckeditor_uploader.fields.RichTextUploadingField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Change RTI/Tenders/Careers',
            },
        ),
    ]
