# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0016_auto_20160708_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, default='C:\\Programming\\Django\\redcross\\redcross_media\\main\\posts\\default.png', upload_to='C:\\Programming\\Django\\redcross\\redcross_media\\upload\\posts\\temporary'),
        ),
    ]
