# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0017_post_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(blank=True, default='C:\\Programming\\Django\\redcross\\redcross_media\\uploads\\posts\\default.png', upload_to='C:\\Programming\\Django\\redcross\\redcross_media\\uploads\\posts\\temporary'),
        ),
    ]
