# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0020_post_preview_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name_plural': 'Newsletter'},
        ),
        migrations.AddField(
            model_name='hometext',
            name='slider_read_more',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hometext',
            name='slider_text_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
