# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 13:33
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0021_auto_20160708_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
