# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 22:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0022_auto_20160709_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
