# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0025_auto_20160711_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='age',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='mobile_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='telephone_no',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
