# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0028_calender_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='email_message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
