# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0030_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AddField(
            model_name='gallery',
            name='album_slug',
            field=models.SlugField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
