# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0031_auto_20160712_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch_number',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='branch_number',
            name='missions',
        ),
        migrations.RemoveField(
            model_name='branch_number',
            name='something',
        ),
        migrations.AddField(
            model_name='branch_number',
            name='bb',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Blood Banks'),
        ),
        migrations.AddField(
            model_name='branch_number',
            name='members',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Member count'),
        ),
        migrations.AddField(
            model_name='branch_number',
            name='pmc',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Primary Health Centres'),
        ),
    ]
