# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0032_auto_20160712_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch_number',
            options={'verbose_name_plural': 'Change Branch/PMC count '},
        ),
    ]
