# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0033_auto_20160712_1644'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calender',
            new_name='Event',
        ),
    ]
