# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0034_auto_20160713_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview_image_name',
            field=models.CharField(editable=False, max_length=150, null=True),
        ),
    ]
