# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0035_post_preview_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
