# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcrossmain', '0036_alert_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_to_post',
            field=models.URLField(editable=False, null=True),
        ),
    ]
