# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 21:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
