# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160710_0336'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='C:\\Programming\\Django\\redcross\\redcross_media\\main\\images\\profdef.png', upload_to='C:\\Programming\\Django\\redcross\\redcross_media\\users\\images\\04:36:03.624340'),
        ),
    ]
